# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banzoufenlei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banzouurl', models.CharField(blank=True, max_length=255, null=True)),
                ('shangchuanshijian', models.CharField(blank=True, max_length=255, null=True)),
                ('geshi', models.CharField(blank=True, max_length=255, null=True)),
                ('shangchuanyonghu', models.CharField(blank=True, max_length=255, null=True)),
                ('yuanchang', models.CharField(blank=True, max_length=255, null=True)),
                ('banzouming', models.CharField(blank=True, max_length=255, null=True)),
                ('zhonglei', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'banzoufenlei',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gedancontentinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danqubofangliang', models.CharField(blank=True, max_length=255, null=True)),
                ('gequzuozhe', models.CharField(blank=True, max_length=255, null=True)),
                ('gequurl', models.CharField(blank=True, max_length=255, null=True)),
                ('gequmingcheng', models.CharField(blank=True, max_length=255, null=True)),
                ('gequxuhao', models.CharField(blank=True, max_length=255, null=True)),
                ('gequshuliang', models.CharField(blank=True, max_length=255, null=True)),
                ('jianjie', models.CharField(blank=True, max_length=255, null=True)),
                ('biaoqian', models.CharField(blank=True, max_length=255, null=True)),
                ('shoucang', models.CharField(blank=True, max_length=255, null=True)),
                ('bofangcishu', models.CharField(blank=True, max_length=255, null=True)),
                ('chuangjianren', models.CharField(blank=True, max_length=255, null=True)),
                ('chuangjianshijian', models.CharField(blank=True, max_length=255, null=True)),
                ('gedan_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gedancontentinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gedaninfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gedanurl', models.CharField(blank=True, max_length=255, null=True)),
                ('zuozhe', models.CharField(blank=True, max_length=255, null=True)),
                ('gedanname', models.CharField(blank=True, max_length=255, null=True)),
                ('bofangliang', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gedaninfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Yuanchuangcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dianzanshu', models.CharField(blank=True, max_length=255, null=True)),
                ('shoucangshu', models.CharField(blank=True, max_length=255, null=True)),
                ('xiazaishu', models.CharField(blank=True, max_length=255, null=True)),
                ('shangchuanshijian', models.CharField(blank=True, max_length=255, null=True)),
                ('xiazaishezhi', models.CharField(blank=True, max_length=255, null=True)),
                ('qufeng', models.CharField(blank=True, max_length=255, null=True)),
                ('yuzhong', models.CharField(blank=True, max_length=255, null=True)),
                ('fenlei', models.CharField(blank=True, max_length=255, null=True)),
                ('hunsuo', models.CharField(blank=True, max_length=255, null=True)),
                ('bianqu', models.CharField(blank=True, max_length=255, null=True)),
                ('zuoqu', models.CharField(blank=True, max_length=255, null=True)),
                ('zuoci', models.CharField(blank=True, max_length=255, null=True)),
                ('yanchang', models.CharField(blank=True, max_length=255, null=True)),
                ('mingzi', models.CharField(blank=True, max_length=255, null=True)),
                ('zhonglei', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'yuanchuangcontent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Yunachuangfenlei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mokuai', models.CharField(blank=True, max_length=255, null=True)),
                ('fenleiurl', models.CharField(blank=True, max_length=255, null=True)),
                ('fenleiname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'yunachuangfenlei',
                'managed': False,
            },
        ),
    ]
